server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://pb-eureka-service:8761/eureka
  instance:
    hostname: pb-gateway-service

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: pb-client-service
          uri: lb://pb-client-service
          predicates:
            - Path=/app/micro/clients/**
        - id: pb-request-service
          uri: lb://pb-request-service
          predicates:
            - Path=/app/micro/requests/**
        - id: pb-myrequests-service
          uri: lb://pb-myrequests-service
          predicates:
            - Path=/app/micro/myrequests/**
        - id: pb-evaluation-service
          uri: lb://pb-evaluation-service
          predicates:
            - Path=/app/micro/evaluation/**
        - id: pb-simulation-service
          uri: lb://pb-simulation-service
          predicates:
            - Path=/app/micro/simulation/**