server:
  port: 8080
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: PBClient
          uri: lb://PBClient
          predicates:
            - Path=/app/micro/clients/**
        - id: PBRequest
          uri: lb://PBRequest
          predicates:
            - Path=/app/micro/requests/**