apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-eureka-deployment
  labels:
    app: pb-eureka-deployment
spec:
  selector:
    matchLabels:
      app: pb-eureka-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pb-eureka-deployment
    spec:
      containers:
        - name: pb-eureka-service
          image: franciscoxd1123/pbeureka
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: pb-eureka-service
  labels:
    app: pb-eureka-service
spec:
  selector:
    app: pb-eureka-deployment
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: NodePort