apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-evaluation-deployment
  labels:
    app: pb-evaluation-deployment
spec:
  selector:
    matchLabels:
      app: pb-evaluation-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pb-evaluation-deployment
    spec:
      containers:
        - name: pb-evaluation-service
          image: franciscoxd1123/pbevaluation
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PBEVALUATION
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PBEVALUATION
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PBEVALUATION
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PBEVALUATION
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PBEVALUATION
---
apiVersion: v1
kind: Service
metadata:
  name: pb-evaluation-service
  labels:
    app: pb-evaluation-service
spec:
  selector:
    app: pb-evaluation-deployment
  ports:
    - protocol: TCP
      port: 8094
      targetPort: 0
  type: NodePort