apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-frontend-deployment
  labels:
    app: pb-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pb-frontend
  template:
    metadata:
      labels:
        app: pb-frontend
    spec:
      containers:
        - name: pbfrontend
          image: franciscoxd1123/pbfrontend
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pb-frontend-service
  labels:
    app: pb-frontend
spec:
  selector:
    app: pb-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001
  type: NodePort