apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-gateway-deployment
  labels:
    app: pb-gateway-deployment
spec:
  selector:
    matchLabels:
      app: pb-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pb-gateway-deployment
    spec:
      containers:
        - name: pb-gateway-service
          image: franciscoxd1123/pbgateway
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pb-gateway-service
  labels:
    app: pb-gateway-service
spec:
  selector:
    app: pb-gateway-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort