apiVersion: apps/v1
kind: Deployment
metadata:
  name: pb-request-deployment
  labels:
    app: pb-request-deployment
spec:
  selector:
    matchLabels:
      app: pb-request-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: pb-request-deployment
    spec:
      containers:
        - name: pb-request-service
          image: franciscoxd1123/pbrequest
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_HOST_PBREQUEST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_PORT_PBREQUEST
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: DB_DBNAME_PBREQUEST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_USER_PBREQUEST
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: DB_PASSWORD_PBREQUEST
---
apiVersion: v1
kind: Service
metadata:
  name: pb-request-service
  labels:
    app: pb-request-service
spec:
  selector:
    app: pb-request-deployment
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 0
  type: NodePort