apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config-map
  labels:
    app: postgres-config-map
data:
  DB_HOST_PBCLIENT: "pb-client-db-service"
  DB_PORT_PBCLIENT: "5432"
  DB_DBNAME_PBCLIENT: "clients"

  DB_HOST_PBREQUEST: "pb-request-db-service"
  DB_PORT_PBREQUEST: "5432"
  DB_DBNAME_PBREQUEST: "requests"

  DB_HOST_PBMYREQUESTS: "pb-myrequests-db-service"
  DB_PORT_PBMYREQUESTS: "5432"
  DB_DBNAME_PBMYREQUESTS: "myrequests"

  DB_HOST_PBEVALUATION: "pb-evaluation-db-service"
  DB_PORT_PBEVALUATION: "5432"
  DB_DBNAME_PBEVALUATION: "evaluation"

  DB_HOST_PBSIMULATION: "pb-simulation-db-service"
  DB_PORT_PBSIMULATION: "5432"
  DB_DBNAME_PBSIMULATION: "simulation"